added code for daily updates monitoring
algoseekgit/aws-infrastructure pull request #9
Opened 2023-08-18 12:15 UTC by RomanMatviiv

2023-08-25 07:29 UTC, TarasKuzyo requested changes

2023-08-25 07:29 UTC, TarasKuzyo commented on daily-updates-monitoring-infrustructure/check_update_status.py
> +    table_name = 'monitoring_db_table'
This line is not used

2023-08-25 07:29 UTC, TarasKuzyo commented on daily-updates-monitoring-infrustructure/check_update_status.py
> +    print(current_time_edt)
Remove debug line

2023-08-25 07:29 UTC, TarasKuzyo commented on daily-updates-monitoring-infrustructure/check_update_status.py
> +        '__trade_date__', (current_time_edt - timedelta(days=bkg_updates['days_offset'])).date().strftime('%Y%m%d')
Assign `(current_time_edt - timedelta(days=bkg_updates['days_offset'])).date().strftime('%Y%m%d')` to a separate var and then reuse

2023-08-25 07:29 UTC, TarasKuzyo commented on daily-updates-monitoring-infrustructure/check_update_status.py
> +        update_times.append(db_record['modified'])
Why do you append this record?

2023-08-25 11:01 UTC, RomanMatviiv commented on daily-updates-monitoring-infrustructure/initialize_crontab.py
> +    api_login_secret = os.getenv('API_LOGIN_SECRET')  # 'CyDMEmLotWsykvOo'
Fixed in the last commit

2023-08-25 11:01 UTC, RomanMatviiv commented on daily-updates-monitoring-infrustructure/check_update_status.py
> +    table_name = 'monitoring_db_table'
Fixed in the last commit

2023-08-25 11:01 UTC, RomanMatviiv commented on daily-updates-monitoring-infrustructure/check_update_status.py
> +    print(current_time_edt)
Fixed in the last commit

2023-08-25 11:01 UTC, RomanMatviiv commented on daily-updates-monitoring-infrustructure/check_update_status.py
> +        '__trade_date__', (current_time_edt - timedelta(days=bkg_updates['days_offset'])).date().strftime('%Y%m%d')
Fixed in the last commit

2023-08-25 11:04 UTC, RomanMatviiv commented on daily-updates-monitoring-infrustructure/check_update_status.py
> +        update_times.append(db_record['modified'])
The db_record['events_log'] value includes the whole history of updates for a specific dataset and trading day except the last update time which is stored in the db_record['modified'].
So, we need all these timestamps for checking updates for datasets with intraday update logic.

2023-08-28 13:42 UTC, TarasKuzyo approved these changes

2023-08-28 13:43 UTC, merged